name: Setup, Lint and Build

on:
  - push

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      python-version: 3.9
      poetry-version: 1.1.6

    steps:
      - name: Repository checkout
        uses: actions/checkout@v2

      - name: Python setup (Python 3.9)
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: Poetry setup
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ env.poetry-version }}

      - name: Setup poetry environment
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path .

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cache
        with:
          path: .virtualenvs
          key: ${{ runner.os }}-${{ env.python-version }}-poetry-${{ env.poetry-version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.python-version }}-poetry-${{ env.poetry-version }}-

      - name: Install dependencies with poetry
        run: |
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path .
      - uses: actions/cache@v2
        id: cache
        with:
          path: .virtualenvs
          key: ${{ runner.os }}-3.9-poetry-1.1.6-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-3.9-poetry-1.1.6-

      - name: Build site
        run: |
          poetry run sphinx-build -b html docs docs/_build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: docs/_build/

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path .
      - uses: actions/cache@v2
        id: cache
        with:
          path: .virtualenvs
          key: ${{ runner.os }}-3.9-poetry-1.1.6-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-3.9-poetry-1.1.6-

      - name: Lint with pylint
        run: |
          poetry run pylint projet
        if: always()

      - name: Lint with pydocstyle
        run: |
          poetry run pydocstyle projet
        if: always()
