name: "Deploy documentation"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Poetry setup
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        uses: allanchain/poetry-cache-action@v0.2.0
        id: cache
        with:
          ensure-module: "pandas"

      - name: Build site
        run: |
          poetry run sphinx-build -b html docs docs/_build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: docs/_build/
