name: Lint the project

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v2
      - name: Poetry setup
        uses: Gr1N/setup-poetry@v4
      - name: Install dependencies
        uses: allanchain/poetry-cache-action@v0.2.0
        id: cache
        with:
          ensure-module: "pandas"

      - name: Lint with pylint
        run: |
          poetry run pylint projet
        if: always()
      #
      # - name: 8/9) Lint with mypy
      #   run: |
      #     # poetry run mypy projet
      # if: always()

      - name: Lint with pydocstyle
        run: |
          poetry run pydocstyle projet
        if: always()
