name: "Poetry"

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      os: ubuntu-latest
      python-version: 3.9
      poetry-version: 1.1.6
    steps:
      - uses: actions/checkout@v2
      - uses: Gr1N/setup-poetry@v4
      - uses: allanchain/poetry-cache-action@v0.2.0
        id: cache
        with:
          ensure-module: "pandas"

      - name: Install dependencies with poetry
        run: |
          poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Build site
        run: |
          poetry run sphinx-build -b html docs docs/_build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: DocumentationHTML
          path: docs/_build/
